# Generated by Django 5.2.8 on 2025-11-28 22:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="court",
            name="hourly_rate",
        ),
    ]
