# Generated by Django 5.2.8 on 2025-12-01 01:40

import django.db.models.deletion
from django.db import migrations, models


def convert_coaches_to_players(apps, schema_editor):
    ClubUser = apps.get_model("core", "ClubUser")
    ClubUser.objects.filter(role="coach").update(role="player")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_court_hourly_rate"),
    ]

    operations = [
        migrations.RunPython(convert_coaches_to_players, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="clubuser",
            name="role",
            field=models.CharField(
                choices=[("admin", "Administrador"), ("player", "Atleta")],
                default="player",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="Coach",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coaches",
                        to="core.club",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
