# Generated by Django 5.2.8 on 2025-12-01 04:14

from django.db import migrations, models


def set_status_forward(apps, schema_editor):
    Reservation = apps.get_model("core", "Reservation")
    Reservation.objects.filter(status__in=["confirmada", "pendente"]).update(status="aprovada")


def set_status_backward(apps, schema_editor):
    Reservation = apps.get_model("core", "Reservation")
    Reservation.objects.filter(status="aprovada").update(status="confirmada")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_cleanup_coach_legacy_columns"),
    ]

    operations = [
        migrations.RunPython(set_status_forward, set_status_backward),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=models.CharField(
                choices=[("aprovada", "Aprovada"), ("cancelada", "Cancelada")],
                default="aprovada",
                max_length=20,
            ),
        ),
    ]
